//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBIT3J_SuperSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogAuditTrail
    {
        public int LogID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Action { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
    }
}
