//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBIT3J_SuperSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SBIT3JEntitiesPOS : DbContext
    {
        public SBIT3JEntitiesPOS()
            : base("name=SBIT3JEntitiesPOS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<LogAuditTrail> LogAuditTrails { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Restock> Restocks { get; set; }
        public virtual DbSet<RestockDetail> RestockDetails { get; set; }
        public virtual DbSet<ReturnsRefund> ReturnsRefunds { get; set; }
        public virtual DbSet<SalesTransaction> SalesTransactions { get; set; }
        public virtual DbSet<SalesTransactionDetail> SalesTransactionDetails { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
