//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBIT3J_SuperSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestockDetail
    {
        public int RestockDetailID { get; set; }
        public Nullable<int> RestockID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> QuantityAdded { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Restock Restock { get; set; }
    }
}
