//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBIT3J_SuperSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnsRefund
    {
        public int ReturnID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> QuantityReturned { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> Resellable { get; set; }
        public string CustomerName { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SalesTransaction SalesTransaction { get; set; }
    }
}
