//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBIT3J_SuperSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTransactionDetail
    {
        public int TransactionDetailID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> QuantitySold { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<int> DiscountID { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual Product Product { get; set; }
        public virtual SalesTransaction SalesTransaction { get; set; }
    }
}
