//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBIT3J_SuperSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesTransaction()
        {
            this.ReturnsRefunds = new HashSet<ReturnsRefund>();
            this.SalesTransactionDetails = new HashSet<SalesTransactionDetail>();
        }
    
        public int TransactionID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> CashierUserID { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string ReceiptInfo { get; set; }

        public IEnumerable<SalesTransactionDetail> ListofOrderDetailViewModel { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnsRefund> ReturnsRefunds { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesTransactionDetail> SalesTransactionDetails { get; set; }
    }
}
